# Generated by Django 5.2.1 on 2025-05-07 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_phone', models.CharField(max_length=15)),
            ],
        ),
    ]
