# Generated by Django 5.2.1 on 2025-05-07 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_type', models.CharField(choices=[('accident', 'Accident'), ('breakdown', 'Vehicle Breakdown'), ('medical', 'Medical Emergency'), ('other', 'Other')], max_length=10)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('reported_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('reported', 'Reported'), ('in_progress', 'In Progress'), ('resolved', 'Resolved')], default='reported', max_length=15)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='trips.trip')),
            ],
        ),
    ]
